name: Release - Development

on:
  pull_request:
    branches:
      - development
    types:
      - closed

permissions:
  packages: write
  contents: read

jobs:
  publish-nuget:  
    if: github.event.pull_request.merged == true
    name: Publish Nuget Package
    runs-on: windows-latest
    env:
      BUILD_CONFIG: Release
      PACKAGE_VERSION: 1.0.${{ github.run_number }}-dev
      GITHUB_NUGET_API_KEY: ${{ secrets.GITHUB_TOKEN }}
      GITHUB_NUGET_URL: https://nuget.pkg.github.com/llott9264/index.json
      
    steps:
    - uses: actions/checkout@v2
    
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '8.x'

    - name: Build NuGet Package
      run: dotnet pack ./src/Utilities.UnitOfWork/Utilities.UnitOfWork.csproj /p:Version=${{ env.PACKAGE_VERSION }} --configuration ${{ env.BUILD_CONFIG }} --output ./artifacts

    - name: Publish NuGet Package
      run: dotnet nuget push ./artifacts/Utilities.UnitOfWork.${{ env.PACKAGE_VERSION }}.nupkg --api-key ${{ env.GITHUB_NUGET_API_KEY }} --source ${{ env.GITHUB_NUGET_URL }} --skip-duplicate
  pull-request-not-merged:
    if: github.event.pull_request.merged == false
    name: Cancel Nuget Package Release
    runs-on: windows-latest
    steps:
    - run: |
        echo Pull Request was not merged with development branch.  Release was canceled.